# ==============================================================
# CI-CD Pipeline to DockerHub test task
# Copyleft (C) Sergey Treiman 2022
# ==============================================================
name: CI-CD-Pipeline-to-DockerHub-test
env:
  APPLICATION_NAME   : "MyFlask"
  ENWIRONMENT_NAME   : "MyFlask-env"
  DEPLOY_PACKAGE_NAME: "flask_app_${{github.sha}}.zip"
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  my_ci_part:
    runs-on: ubuntu-latest
    
    env:
      VAR1: "Thes is Job Level Variables1"
      VAR2: "Thes is Job Level Variables2"
      
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Git colne my repo
        uses: actions/checkout@v2
        
      - name: Print env vars
        run: |
          echo "Var1 = ${{env.VAR1}}"
          echo "Var2 = ${{env.VAR2}}"
          echo "Var3 = $LOCAL_VAR"
        env:
          LOCAL_VAR: "This is Superr local Enviromment variable"

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          
      - name: Execure few commands
        run: |
          echo "Application name: ${{ env.APPLICATION_NAME }}"
          echo "Deplyo pakcage name is: ${{ env.DEPLOY_PACKAGE_NAME }}"
          
      - name: List corrent folder
        run: ls -la
        
      - name: Lets test some packages iof the are here
        run: |
          aws --version
          zip --version
