# ==============================================================
# CI-CD Pipeline to DockerHub test task
# Copyleft (C) Sergey Treiman 2022
# ==============================================================
name: CI-CD-Pipeline-to-DockerHub-test

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  my_ci_part:
    runs-on: ubuntu-latest
      
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Git colne my repo
        uses: treyman/github@v2

          
      - name: Configure my DockerHub Credentials
        uses: docker/github@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: treyman/next
